sudo: required

services:
  - docker

before_install:
  - docker build -t willyhui94/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true willyhui94/react-test yarn run test -- --coverage

after_success:
  - docker build -t willyhui94/multi-client ./client
  - docker build -t willyhui94/multi-nginx ./nginx
  - docker build -t willyhui94/multi-server ./server
  - docker build -t willyhui94/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push willyhui94/multi-client
  - docker push willyhui94/multi-nginx
  - docker push willyhui94/multi-server
  - docker push willyhui94/multi-worker
